[LeanTeX]
; The directory where Jixia is installed
; Note: I am currently using my own fork of Jixia, which adds expression metadata to elab
Jixia = C:/Users/hmesh/Documents/jixia/.lake/build/bin/jixia.exe

; The directory where LeanTeX should store files it uses
WorkingDir = .leantex

; The path to the Lean code to be processed
CodePath = ./examples/Propositional.lean