[LeanTeX]
; The directory where Jixia is installed
Jixia = ~/Programs/jixia/.lake/build/bin/jixia

; The directory where LeanTeX should store files it uses
; WorkingDir = .leantex

; The path to the Lean code to be processed
; CodePath = examples/True.lean